BaseURL = "https://base-url-here/"
relativeURLs = false
languageCode = "en-us"
title = "Mike Jick | PGA Golf Professional"
disqusShortname = ""
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"
	post = "posts"

[params]
	# Render the rotating globe in the sidebar
	showglobe = false

	# Include favicon
	favicon = "mj-icon.png"

	# Google Analytics
	analytics = "SHORT-CODE-HERE"

	# Email (optional)
	email = ""

	# Header Title for the main page
	header = "What I'm Thinking"

	# Sidebar profile picture
	profilepic = "img/mikejick-logo-min.jpg"

	# Title/subtitle for the sidebar
	title = "Mike Jick"
	subtitle = "PGA Professional"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "envelope"
	url = "contact/"
	[[params.socialbuttons]]
	faicon = "rss"
	url = "newsletter/"
	# [[params.socialbuttons]]
	# faicon = "github"
	# url = "https://github.com/"
	# [[params.socialbuttons]]
	# faicon = "twitter"
	# url = "https://twitter.com/"
	# [[params.socialbuttons]]
	# faicon = "linkedin"
	# url = "https://linkedin.com"
	# [[params.socialbuttons]]
	# faicon = "google-plus"
	# url = "https://plus.google.com/+YourID"

	# Nav links below the profile picture
	[[params.navlinks]]
	name = "About"
	url = "about/"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"

	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"
